name: Spriggit Fix Form ID Collisions
description:
  Fixes any Form ID collisions in your plugin/master, usually done after a
  merge.
author: yak3d

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: shuffle
  color: green

# Define your inputs here.
inputs:
  spriggitVersion:
    description: The version of Spriggit to install
    required: true
    default: '0.38.5'
  pluginPath:
    description: The path to the serialized plugin data
    required: true

runs:
  using: node20
  main: dist/index.js
